### ISSUE TITLE
Automate monitor settings

### ISSUE THREAD

**Issue by phisch** [phisch/dotfiles#2]
Depending on which monitors are connected, a predefined xrandr config should be used. If no xrandr config matches the connected monitors, each monitor should use its maximum resolution and refresh rate and monitors should be positioned in the order they are listed in xrandr.

Additionally, attaching or detaching a monitor should trigger the monitors to be re-configured.

**Comment by Lem** [comment]
I'm using [autorandr](https://github.com/phillipberndt/autorandr) for this.
