### ISSUE TITLE
Fails at paritioning

### ISSUE THREAD

**Issue by Jaksuhn** [phisch/dotfiles#3]
Fresh VM instance, able to install arch regularly. Thought it was just my modifications to this but using your own install file (via the curl command in the readme) produces the same result.

```
Adding partition to BlockDevice(/dev/sda)
Adding partition to BlockDevice(/dev/sda)
Traceback (most recent call last):
    File "/proc/self/fd/11", line 62, in <module>
    File "/usr/lib/python3.9/site-packages/archinstall/lib/disk.py", line 477, in __exit__
        raise args[1]
    File "/proc/self/fd/11", line 54, in <module>
    File "/usr/lib/python3.9/site-packages/archinstall/lib/disk.py", line 510, in use_entire_disk
        self.blockdevice.patition[0].filesystem = 'vfat'
IndexError: list index out of range
```

**Comment by phisch** [comment]
Uhm, this isn't really a repo where you'd report issues, it is just my personal setup/dotfiles.
Aside from that, this looks like some issue with your drives. No idea tbh. Archinstall will get a newer/better partitioner eventually anyway.

**Comment by Jaksuhn** [comment]
Yeah I realise this isn't a regular repo. Was just kind of desperate at this point because I've been on and off trying to figure this out for the last month and was hoping you might know something that would help. Apologies for the inconvenience.

**Comment by phisch** [comment]
@Jaksuhn don't worry. I have seen similar issues on the archinstall discord. Maybe it is related to some weird existing partitioning on your hard drive. Maybe just hop on their discord and search for similar errors.
